### PR TITLE
build: use errorprone's GuardedBy rather than javax's

### PR DESCRIPTION
**Pull request by suztomo**
Towards #1938 . This pull request replaces `javax.annotation.concurrent.GuardedBy` with errorprone's annotation. The official documentation https://github.com/google/error-prone/blob/master/docs/bugpattern/GuardedBy.md uses `com.google.errorprone.annotations.concurrent.GuardedBy`.

To reviewers, if you wonder whether the GuardedBy annotation has any effect, see the Bazel build caught a bug I intentionally introduced in https://github.com/googleapis/sdk-platform-java/pull/2060.

### CODE REVIEW

**Comment by blakeli0** [comment]
I guess this is one of the effort to replace all Javax annotation usages?

**Comment by suztomo** [comment]
> external/com_google_api_gax_java/gax/src/main/java/com/google/api/gax/rpc/ServerStreamingAttemptCallable.java:110: error: could not resolve GuardedBy

**Comment by suztomo** [comment]
> I guess this is one of the effort to replace all Javax annotation usages?

@blakeli0 Yes, this change is towards the goal. However, we use tools that still use the javax annotations (https://github.com/googleapis/sdk-platform-java/issues/1938#issuecomment-1737899388) and, fortunately, there's no known problems in using javax annotations so far. I don't think we will replace the javax annotations completely anytime soon.

**Comment by blakeli0** [comment]
> I don't think we will replace the javax annotations completely anytime soon.

If this is the case, do we want to pursue more replacements of javax annotations at this moment?

File: gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientCallImpl.java [hunk 1]
```diff
@@ -35,6 +35,7 @@
 import com.google.api.gax.httpjson.HttpRequestRunnable.RunnableResult;
 import com.google.api.gax.rpc.StatusCode;
 import com.google.common.base.Preconditions;
+import com.google.errorprone.annotations.concurrent.GuardedBy;
```
[the remark this answers is not in the document]
Comment (suztomo) [reply gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientCallImpl.java:38]: https://errorprone.info/bugpattern/GuardedBy

> Note: there are a couple more annotations called @GuardedBy, including javax.annotation.concurrent.GuardedBy and org.checkerframework.checker.lock.qual.GuardedBy. The check recognizes those versions of the annotation, but we recommend using com.google.errorprone.annotations.concurrent.GuardedBy.

So errorprone treats the GuardedBy annotations from errorprone and javax in the same manner.

**Comment by suztomo** [comment]
> do we want to pursue more replacements of javax annotations at this moment?

@blakeli0 Not for this pull request. This GuardedBy is the first one I can easily move. We may find replacements for other annotations listed in https://github.com/googleapis/sdk-platform-java/issues/1938. We'll have another pull request at that time.

**Review by blakeli0 — APPROVED** [review]

**Comment by blakeli0** [comment]
> > do we want to pursue more replacements of javax annotations at this moment?
> 
> @blakeli0 Not for this pull request. This GuardedBy is the first one I can easily move. We may find replacements for other annotations listed in #1938. We'll have another pull request at that time.

Thanks, this PR LGTM. What I'm concerning is that should we keep the issue https://github.com/googleapis/sdk-platform-java/issues/1938 in our ready-to-fix backlog. We should move it out if we think it will not be fixed anytime soon.

**Comment by suztomo** [comment]
I'll create child issues for each annotations.

**Comment by suztomo** [comment]
https://github.com/googleapis/sdk-platform-java/issues/2063
